[build.environment]
  YARN_VERSION = "1.13.0"

[build]
  command = "npm config set scripts-prepend-node-path true && yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "npm config set scripts-prepend-node-path true && yarn build:preview"
